[platformio]
default_envs = xiao_esp32c3

[env]
framework = arduino
monitor_speed = 115200
extra_scripts = pre:tools/embed_web.py
lib_ldf_mode = deep+
build_src_flags = -Wall -Wextra

[esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

[pico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
board_build.core = earlephilhower

[env:xiao_esp32c3]
extends = esp32c3
build_flags = ${esp32c3.build_flags} -DTUBEPI_SOURCE=0

[env:xiao_esp32c3_pulse]
extends = esp32c3
build_flags = ${esp32c3.build_flags} -DTUBEPI_SOURCE=1

[env:xiao_esp32c3_sim]
extends = esp32c3
build_flags = ${esp32c3.build_flags} -DTUBEPI_SOURCE=2

[env:pico2w]
extends = pico2w
build_flags = -DTUBEPI_SOURCE=0

[env:pico2w_pulse]
extends = pico2w
build_flags = -DTUBEPI_SOURCE=1

[env:pico2w_sim]
extends = pico2w
build_flags = -DTUBEPI_SOURCE=2
