#pragma once

#define TUBEPI_SOURCE_ANALOG 0
#define TUBEPI_SOURCE_PULSE 1
#define TUBEPI_SOURCE_SIMULATED 2

#ifndef TUBEPI_SOURCE
#define TUBEPI_SOURCE TUBEPI_SOURCE_ANALOG
#endif

#ifndef TUBEPI_AP_SSID
#define TUBEPI_AP_SSID "TG1B-PI"
#endif

#ifndef TUBEPI_AP_PASSWORD
#define TUBEPI_AP_PASSWORD ""
#endif

#ifndef TUBEPI_AP_CHANNEL
#define TUBEPI_AP_CHANNEL 6
#endif

#ifndef TUBEPI_AP_MAX_CLIENTS
#define TUBEPI_AP_MAX_CLIENTS 4
#endif

#ifndef TUBEPI_ANALOG_DECIMATION
#define TUBEPI_ANALOG_DECIMATION 4
#endif

#ifndef TUBEPI_ANALOG_BITS_LSB
#define TUBEPI_ANALOG_BITS_LSB 0
#endif

#ifndef TUBEPI_PULSE_BITS_LSB
#define TUBEPI_PULSE_BITS_LSB 0
#endif

#ifndef TUBEPI_VON_NEUMANN
#if TUBEPI_SOURCE == TUBEPI_SOURCE_PULSE
#define TUBEPI_VON_NEUMANN 0
#else
#define TUBEPI_VON_NEUMANN 1
#endif
#endif

#ifndef TUBEPI_ASSUMED_ENTROPY
#if TUBEPI_SOURCE == TUBEPI_SOURCE_PULSE
#define TUBEPI_ASSUMED_ENTROPY 1.0
#else
#define TUBEPI_ASSUMED_ENTROPY 2.0
#endif
#endif

#ifndef TUBEPI_QUIET_SIGMA
#if TUBEPI_SOURCE == TUBEPI_SOURCE_PULSE
#define TUBEPI_QUIET_SIGMA 2.0
#else
#define TUBEPI_QUIET_SIGMA 4.0
#endif
#endif

#ifndef TUBEPI_MONITOR_WINDOW
#if TUBEPI_SOURCE == TUBEPI_SOURCE_PULSE
#define TUBEPI_MONITOR_WINDOW 1024
#else
#define TUBEPI_MONITOR_WINDOW 16384
#endif
#endif

#ifndef TUBEPI_PULSE_MIN_GAP_US
#define TUBEPI_PULSE_MIN_GAP_US 20
#endif

#ifndef TUBEPI_PULSE_RANGE_US
#define TUBEPI_PULSE_RANGE_US 20000
#endif

#ifndef TUBEPI_HV_ENABLE_PIN
#define TUBEPI_HV_ENABLE_PIN -1
#endif

#ifndef TUBEPI_WARMUP_MS
#define TUBEPI_WARMUP_MS 30000
#endif
